### ISSUE TITLE
How to use as a GitHub Action?

### ISSUE THREAD

**Issue by orhun** [crate-ci/committed#320]
Hello! 🐻

I'm trying to use `committed` as a GitHub Action as follows:

```yml
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: "Check conventional commits"
        uses: crate-ci/committed@master
```

However, I'm getting this:

```
Linting commits:
fatal: ambiguous argument 'HEAD~..HEAD^2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:

Against 'committed.toml':
'git <command> [<revision>...] -- [<file>...]'
parent 1 does not exist; class=Invalid (3); code=NotFound (-3)
subject_length = 0
subject_capitalized = false
subject_not_punctuated = true
imperative_subject = true
no_fixup = true
no_wip = true
hard_line_length = 0
line_length = 0
style = 'conventional'
allowed_types = [
    'fix',
    'feat',
    'chore',
    'docs',
    'style',
    'refactor',
    'perf',
    'test',
]
merge_commit = false

If this fails, don't sweat it. We're trying to encourage clear communication and not hinder contributions.
If it is a reasonable issue and you lack time or feel uncomfortable fixing it yourself,
let us know and we can mentor or fix it.
```

This is due to hardcoded `HEAD~..HEAD^2` in the action:

https://github.com/crate-ci/committed/blob/dc0bcf827cdda383cf2805b673a4b2b44db8de64/docker/entrypoint.sh#L28

```
$ git log --color=always --graph --oneline HEAD~..HEAD^2

fatal: ambiguous argument 'HEAD~..HEAD^2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Is there a way to configure this to e.g. pass only `HEAD`?
