### ISSUE TITLE
Config file not supported? 

### ISSUE THREAD

**Issue by BenLeadbetter** [crate-ci/committed#360]
Hi, nice tool!

I had a poke around and found the --config and --dump-config arguments to the committed exec. I tried out the following:

```bash
committed --dump-config .committed-config
```

And set my .pre-commit-config to read from this file:
```yaml
- repo: https://github.com/crate-ci/committed
  rev: v1.0.20
  hooks:
  - id: committed
    args: [--config, .committed-config]
```

However, this makes the hook fail with the following error:

```
failed to parse revision specifier - Invalid pattern '.git/COMMIT_EDITMSG'; class=Invalid (3); code=InvalidSpec (-12)
```

Is this workflow not supported? Is there another way to specify configuration via my `.pre-commit-config` file? From the output of --dump-config, it looks like there's some nice configuration options there which I would love to try out.

Thanks
