### ISSUE TITLE
False positive on imperative mood check due to adverb

### ISSUE THREAD

**Issue by ejpcmac** [crate-ci/committed#393]
## Problem description

In `committed 1.0.20`, using the following configuration:

```toml
style = "conventional"
subject_capitalized = false
allowed_types = ["feat"]
```

Let the following message:

```
feat: always use a given behaviour
```

`committed` reports the following error:

```
error Subject should be in the imperative mood but found `always`
```

## Expected behaviour

“Always use a given behaviour.” is actually in imperative mood, but the verb is in second position, after an adverb. This should not report an error.
